export const SIGN_IN = "SIGN_IN";
export const SIGN_OUT = "SIGN_OUT";
export const AUTH_DOCTOR = "AUTH_DOCTOR";

export const FETCH_DOCTORS = "FETCH_DOCTORS";
export const FETCH_PATIENTS = "FETCH_PATIENTS";

export const ADD_APPOINTMENT = "ADD_APPOINTMENT";
export const FETCH_APPOINTMENTS = "FETCH_APPOINTMENTS";
export const FETCH_DOCTOR_APPOINTMENTS_BY_DATE = "FETCH_DOCTOR_APPOINTMENTS_BY_DATE";
export const CANCEL_APPOINTMENT = "CANCEL_APPOINTMENT";

export const FETCH_AVAILABLE_TIMESLOTS = "FETCH_AVAILABLE_TIMESLOTS";